name: System Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Build the main system executable
    - name: Build readsystem executable
      run: gcc -fprofile-arcs -ftest-coverage -o readsystem main.c readsystem.c

    # Build the usage_display executable
    - name: Build usage_display executable
      run: |
        gcc 
        -IC:/msys64/ucrt64/bin/../include/gtk-4.0 `
        -IC:/msys64/ucrt64/bin/../include/pango-1.0 `
        -IC:/msys64/ucrt64/bin/../include/gdk-pixbuf-2.0 `
        -IC:/msys64/ucrt64/bin/../include/cairo `
        -IC:/msys64/ucrt64/bin/../include/harfbuzz `
        -IC:/msys64/ucrt64/bin/../include/freetype2 `
        -IC:/msys64/ucrt64/bin/../include/graphene-1.0 `
        -IC:/msys64/ucrt64/bin/../lib/graphene-1.0/include `
        -mfpmath=sse -msse -msse2 `
        -IC:/msys64/ucrt64/bin/../include `
        -IC:/msys64/ucrt64/bin/../include/glib-2.0 `
        -IC:/msys64/ucrt64/bin/../lib/glib-2.0/include `
        -IC:/msys64/ucrt64/bin/../include/fribidi `
        -IC:/msys64/ucrt64/bin/../include/webp `
        -DLIBDEFLATE_DLL `
        -IC:/msys64/ucrt64/bin/../include/libpng16 `
        -IC:/msys64/ucrt64/bin/../include/pixman-1 `
        -o usage_display usage_display.c readsystem.c `
        -LC:/msys64/ucrt64/bin/../lib `
        -lgtk-4 -lpangowin32-1.0 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz `
        -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgraphene-1.0 `
        -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl

    # Run the readsystem executable and collect output
    - name: Run readsystem Tests
      run: ./readsystem.exe > test_readsystem.txt

    # Run the usage_display executable
    - name: Run usage_display
      run: ./usage_display.exe > test_usage_display.txt

    # Generate gcov report for coverage
    - name: Generate Coverage Report
      run: |
        gcov readsystem-main.c > main_gcov_report.txt
        gcov readsystem-readsystem.c > readsystem_gcov_report.txt
        gcov readsystem-usage_display.c > usage_display_gcov_report.txt

    # Upload gcov report as an artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: gcov-report
        path: |
          main_gcov_report.txt
          readsystem_gcov_report.txt
          usage_display_gcov_report.txt

    # Upload executable outputs as artifacts
    - name: Upload Test Outputs
      uses: actions/upload-artifact@v3
      with:
        name: system-monitor-test
        path: |
          test_readsystem.txt
          test_usage_display.txt

    # Clean up the workspace
    - name: Clean up
      shell: pwsh
      run: |
        Remove-Item readsystem.exe -Force
        Remove-Item usage_display.exe -Force
        Remove-Item output.txt -Force
        Remove-Item test_readsystem.txt -Force
        Remove-Item test_usage_display.txt -Force
        Remove-Item main_gcov_report.txt -Force
        Remove-Item readsystem_gcov_report.txt -Force
        Remove-Item usage_display_gcov_report.txt -Force
