name: System Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Build the project
    - name: Build the executable
      run: gcc -o readsystem readsystem.c

    # Run unit tests and collect coverage
    - name: Run Tests and Generate Coverage
      run: |
        gcc -fprofile-arcs -ftest-coverage -o readsystem readsystem.c
        ./readsystem.exe > output.txt
        gcov readsystem.c

    # Upload coverage report as an artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: "*.gcov"

    # Upload executable output as an artifact
    - name: Upload Executable Output
      uses: actions/upload-artifact@v3
      with:
        name: system-monitor-output
        path: output.txt

    # Clean up the workspace
    - name: Clean up
      shell: pwsh
      run: |
        Remove-Item readsystem.exe -Force
        Remove-Item output.txt -Force
        Remove-Item *.gcov -Force
