name: System Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install MSYS2 and GTK dependencies
    - name: Setup MSYS2 and Install GTK
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gtk4
          mingw-w64-x86_64-pkg-config
        msystem: MINGW64

    # Ensure MSYS2 is prioritized in PATH
    - name: Update PATH for MSYS2
      run: |
        echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
        echo "C:/msys64/mingw64/lib/pkgconfig" >> $GITHUB_ENV

    # Debugging: Check GCC, pkg-config, and gtk4.pc paths
    - name: Debugging GTK4 Setup
      shell: bash
      run: |
        echo "Checking GCC version:"
        gcc --version

        echo "Checking pkg-config version:"
        pkg-config --version

        echo "Checking pkg-config paths:"
        echo $PKG_CONFIG_PATH

        echo "Checking gtk4.pc location:"
        ls /c/msys64/mingw64/lib/pkgconfig/ || echo "gtk4.pc not found"

        echo "Checking GTK4 CFLAGS:"
        pkg-config --cflags gtk4 || echo "Error retrieving cflags"

        echo "Checking GTK4 LIBS:"
        pkg-config --libs gtk4 || echo "Error retrieving libs"

    # Build readsystem executable
    - name: Build readsystem executable
      shell: bash
      run: gcc -fprofile-arcs -ftest-coverage -o readsystem main.c readsystem.c

    # Build usage_display executable
    - name: Build usage_display executable
      shell: bash
      run: |
        gcc $(pkg-config --cflags gtk4) usage_display.c readsystem.c $(pkg-config --libs gtk4) -o usage_display

    # Test usage_display by ensuring the GUI opens
    - name: Test usage_display GUI
      shell: bash
      run: |
        ./usage_display.exe &
        sleep 5
        tasklist | grep usage_display.exe || exit 1
