name: Build and Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install GCC
    - name: Install GCC
      run: |
        choco install mingw

    # Build with coverage
    - name: Build with coverage
      run: |
        gcc -fprofile-arcs -ftest-coverage -mconsole -o readsystem main.c readsystem.c

    # Run tests and generate coverage
    - name: Run tests
      run: |
        .\readsystem
        gcov main.c readsystem.c

    # Upload coverage results
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: "*.gcov"
