name: System Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install MSYS2 and GTK dependencies
    - name: Setup MSYS2 and Install GTK
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gtk4
          mingw-w64-x86_64-pkg-config
        msystem: mingw64

    # Ensure MSYS2 is prioritized in PATH
    - name: Update PATH for MSYS2
      run: |
        echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
        echo "C:/msys64/usr/bin" >> $GITHUB_PATH

    # Verify pkg-config from MSYS2
    - name: Verify pkg-config
      run: where pkg-config

    # Build the readsystem executable
    - name: Build readsystem executable
      shell: bash
      run: gcc -fprofile-arcs -ftest-coverage -o readsystem main.c readsystem.c

    # Build the usage_display executable
    - name: Build usage_display executable
      shell: bash
      run: |
        export PATH=/usr/bin:/mingw64/bin:$PATH
        /mingw64/bin/gcc $(/mingw64/bin/pkg-config --cflags gtk4) usage_display.c readsystem.c $(/mingw64/bin/pkg-config --libs gtk4) -o usage_display

    # Test usage_display by ensuring the GUI opens
    - name: Test usage_display GUI
      shell: bash
      run: |
        ./usage_display.exe &
        sleep 5
        tasklist | grep usage_display.exe || exit 1

    # Run readsystem executable and collect output
    - name: Run readsystem Tests
      shell: bash
      run: ./readsystem.exe > test_readsystem.txt

    # Generate gcov report for coverage
    - name: Generate Coverage Report
      shell: bash
      run: |
        gcov readsystem-main.c > main_gcov_report.txt
        gcov readsystem-readsystem.c > readsystem_gcov_report.txt
        gcov readsystem-usage_display.c > usage_display_gcov_report.txt

    # Upload gcov report as an artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: gcov-report
        path: |
          main_gcov_report.txt
          readsystem_gcov_report.txt
          usage_display_gcov_report.txt

    # Upload test outputs as artifacts
    - name: Upload Test Outputs
      uses: actions/upload-artifact@v4
      with:
        name: system-monitor-test
        path: |
          test_readsystem.txt

    # Clean up the workspace
    - name: Clean up
      shell: pwsh
      run: |
        Remove-Item readsystem.exe -Force
        Remove-Item usage_display.exe -Force
        Remove-Item output.txt -Force
        Remove-Item test_readsystem.txt -Force
        Remove-Item main_gcov_report.txt -Force
        Remove-Item readsystem_gcov_report.txt -Force
        Remove-Item usage_display_gcov_report.txt -Force
