name: System Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clean workspace
      run: |
        del *.gcno
        del *.gcda
        del readsystem.exe

    - name: Check GCC and gcov versions
      run: |
        gcc --version
        gcov --version

    - name: Build the executable
      run: gcc -fprofile-arcs -ftest-coverage -mconsole -o readsystem main.c readsystem.c

    - name: Run Tests
      run: ./readsystem.exe > test.txt || exit 1

    - name: List workspace files
      run: dir /s /b

    - name: Generate Coverage Report
      run: |
        gcov main.c > gcov_main_report.txt
        gcov readsystem.c > gcov_report.txt

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: gcov-report
        path: |
          gcov_main_report.txt
          gcov_report.txt

    - name: Upload Executable Output
      uses: actions/upload-artifact@v3
      with:
        name: system-monitor-output
        path: test.txt

    - name: Clean up
      shell: pwsh
      run: |
        Remove-Item readsystem.exe -Force
        Remove-Item test.txt -Force
        Remove-Item gcov_report.txt -Force
        Remove-Item gcov_main_report.txt -Force
#RANVIR THIS IS WHERE OUR MAKE IS 
    # Build Window Display
    - name: build Usage Display executable
      run: gcc -o usage_display --coverage usage_display.c 
    # Window display coverage report
    - name: Generate Coverage Report
      run: gcov usage_display-usage_display.c > gcov_DisplayReport.txt
    # Upload gcov report as an artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: gcov_DisplayReport
        path: gcov_DisplayReport.txt
#THIS IS WHERE IT IS STOPS

    # Clean up the workspace
    - name: Clean up
      shell: pwsh
      run: |
        Remove-Item readsystem.exe -Force
        Remove-Item test.txt -Force
        Remove-Item gcov_report.txt -Force
