name: System Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Build the project
    - name: Build the executable
      run: gcc -o readsystem readsystem.c

    # Run the executable and redirect output to a file
    - name: Run the executable and redirect output
      run: .\readsystem.exe > output.txt

    # Upload output.txt as an artifact
    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: system-monitor-output
        path: output.txt

    # Clean up the workspace
    - name: Clean up
      shell: pwsh
      run: |
        Remove-Item readsystem.exe -Force
        Remove-Item output.txt -Force
