name: System Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install MSYS2 and GTK dependencies
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gtk4
          mingw-w64-x86_64-pkg-config

    # Build the main system executable
    - name: Build readsystem executable
      shell: bash
      run: |
        export PATH="/ucrt64/bin:$PATH"
        gcc -fprofile-arcs -ftest-coverage -o readsystem main.c readsystem.c

    # Build the usage_display executable
    - name: Build usage_display executable
      shell: bash
      run: |
        export PATH="/ucrt64/bin:$PATH"
        gcc $(pkg-config --cflags gtk4) usage_display.c readsystem.c $(pkg-config --libs gtk4) -o usage_display

    # Run the readsystem executable and collect output
    - name: Run readsystem Tests
      shell: bash
      run: ./readsystem.exe > test_readsystem.txt

    # Test usage_display by launching it
    - name: Test usage_display GUI
      shell: bash
      run: |
        ./usage_display.exe &
        sleep 5
        tasklist | grep usage_display.exe || exit 1

    # Generate gcov report for coverage
    - name: Generate Coverage Report
      shell: bash
      run: |
        gcov readsystem-main.c > main_gcov_report.txt
        gcov readsystem-readsystem.c > readsystem_gcov_report.txt
        gcov readsystem-usage_display.c > usage_display_gcov_report.txt

    # Upload gcov report as an artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: gcov-report
        path: |
          main_gcov_report.txt
          readsystem_gcov_report.txt
          usage_display_gcov_report.txt

    # Upload executable outputs as artifacts
    - name: Upload Test Outputs
      uses: actions/upload-artifact@v3
      with:
        name: system-monitor-test
        path: |
          test_readsystem.txt

    # Clean up the workspace
    - name: Clean up
      shell: pwsh
      run: |
        Remove-Item readsystem.exe -Force
        Remove-Item usage_display.exe -Force
        Remove-Item output.txt -Force
        Remove-Item test_readsystem.txt -Force
        Remove-Item main_gcov_report.txt -Force
        Remove-Item readsystem_gcov_report.txt -Force
        Remove-Item usage_display_gcov_report.txt -Force
